/**
 * ImmoRadar demo seed.
 *
 * Builds a fully demonstrable environment WITHOUT touching any real website:
 * - 5 agencies, 15 users, ~25 territories
 * - ~500 CRM contacts (with interactions and property relationships)
 * - ~150 properties / ~250 listings / ~750 snapshots, generated by running
 *   backdated listing timelines through the REAL ingestion pipeline, so
 *   snapshots, events (price drops, stale, removed, relisted, FSBO) and
 *   property matching are all authentic engine output.
 * - Scenarios A-E from the product brief.
 * - Opportunities, LeadRevive scans, alerts and workflow history.
 *
 * Idempotent by wiping first. Run: npm run db:seed
 */

import { PrismaClient, type Prisma } from "../src/generated/prisma";
import { hashPassword } from "../src/lib/auth/password";
import { IngestionService } from "../src/ingestion/ingestion-service";
import { OpportunityService } from "../src/services/opportunity-service";
import { LeadReviveService } from "../src/services/leadrevive-service";
import { AlertService } from "../src/services/alert-service";
import { DigestService } from "../src/services/digest-service";
import { WorkflowService } from "../src/services/workflow-service";
import type { RawListing } from "../src/domain/listing/types";
import { normalizeListing } from "../src/normalization/listing-normalizer";

const prisma = new PrismaClient();

// Deterministic RNG so the demo is reproducible
function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(20260816);
const pick = <T>(arr: readonly T[]): T => arr[Math.floor(rand() * arr.length)]!;
const randInt = (min: number, max: number) => min + Math.floor(rand() * (max - min + 1));
const chance = (p: number) => rand() < p;

const NOW = new Date();
const daysAgo = (d: number, hourJitter = true) =>
  new Date(NOW.getTime() - d * 86_400_000 - (hourJitter ? randInt(0, 10) * 3_600_000 : 0));

const FIRST_NAMES = ["Pieter", "An", "Thomas", "Griet", "Karel", "Els", "Jan", "Marie", "Wim", "Sofie", "Bart", "Lien", "Koen", "Eva", "Dirk", "Lore", "Stijn", "Ilse", "Geert", "Nele", "Tom", "Katrien", "Luc", "Veerle", "Joris", "Tine", "Frank", "Mieke", "Hans", "Leen"] as const;
const LAST_NAMES = ["Janssens", "Peeters", "Maes", "Jacobs", "Willems", "Claes", "Goossens", "Wouters", "De Smet", "Vermeulen", "De Clercq", "Desmet", "Dubois", "Lambert", "Martens", "Van Damme", "Pauwels", "Hermans", "Aerts", "De Backer", "Segers", "Lemmens", "Verhoeven", "Michiels", "Van den Berghe"] as const;
const STREETS = ["Veldstraat", "Kerkstraat", "Stationsstraat", "Molenstraat", "Schoolstraat", "Nieuwstraat", "Dorpsstraat", "Brugsesteenweg", "Kortrijksesteenweg", "Antwerpsesteenweg", "Leopoldlaan", "Koning Albertlaan", "Zandberg", "Hoogstraat", "Lange Violettestraat", "Visserij", "Coupure", "Ottergemsesteenweg", "Zwijnaardsesteenweg", "Gebroeders De Smetstraat"] as const;

interface City { postalCode: string; city: string }
const GENT_CITIES: City[] = [
  { postalCode: "9000", city: "Gent" },
  { postalCode: "9030", city: "Mariakerke" },
  { postalCode: "9040", city: "Sint-Amandsberg" },
  { postalCode: "9050", city: "Gentbrugge" },
];
const OTHER_CITIES: City[] = [
  { postalCode: "8000", city: "Brugge" },
  { postalCode: "8400", city: "Oostende" },
  { postalCode: "2000", city: "Antwerpen" },
  { postalCode: "2018", city: "Antwerpen" },
  { postalCode: "2600", city: "Berchem" },
  { postalCode: "3000", city: "Leuven" },
  { postalCode: "3001", city: "Heverlee" },
  { postalCode: "3500", city: "Hasselt" },
  { postalCode: "3600", city: "Genk" },
  { postalCode: "9100", city: "Sint-Niklaas" }, // outside every demo territory
  { postalCode: "1000", city: "Brussel" }, // outside every demo territory
];
const ALL_CITIES = [...GENT_CITIES, ...OTHER_CITIES];

const PRIVATE_DESCRIPTIONS = [
  "Verkoop door particulier, zonder makelaar. Vrij bij akte.",
  "Rechtstreeks van eigenaar. Particulier à particulier, immokantoren onthouden zich.",
  "Te koop van particulier: instapklare woning, geen makelaar.",
] as const;
const PRO_DESCRIPTIONS = [
  "Aangeboden door erkend vastgoedmakelaar. Contacteer ons immokantoor voor een bezoek.",
  "Exclusief in portefeuille bij ons vastgoedkantoor.",
] as const;
const AGENCY_NAMES = ["Immo Deluxe", "Vastgoed Partners", "Habitat Plus", "Domus Invest"] as const;

async function wipe() {
  // Order matters: children first
  await prisma.auditLog.deleteMany();
  await prisma.alert.deleteMany();
  await prisma.alertRule.deleteMany();
  await prisma.opportunityActivity.deleteMany();
  await prisma.opportunityAssignment.deleteMany();
  await prisma.opportunityScore.deleteMany();
  await prisma.opportunitySignal.deleteMany();
  await prisma.opportunity.deleteMany();
  await prisma.contactPropertyRelationship.deleteMany();
  await prisma.crmImportRow.deleteMany();
  await prisma.crmImport.deleteMany();
  await prisma.crmInteraction.deleteMany();
  await prisma.crmContact.deleteMany();
  await prisma.listingEvent.deleteMany();
  await prisma.listingSnapshot.deleteMany();
  await prisma.sellerIdentity.deleteMany();
  await prisma.agencyIdentity.deleteMany();
  await prisma.listing.deleteMany();
  await prisma.property.deleteMany();
  await prisma.collectorRun.deleteMany();
  await prisma.source.deleteMany();
  await prisma.territory.deleteMany();
  await prisma.user.deleteMany();
  await prisma.agency.deleteMany();
}

async function main() {
  console.log("Seeding ImmoRadar demo environment...");
  await wipe();

  // --- Sources -------------------------------------------------------------
  const portalA = await prisma.source.create({
    data: { code: "fixture-portal-a", name: "Fixture Portal A", kind: "fixture", pollIntervalMinutes: 30 },
  });
  const portalB = await prisma.source.create({
    data: { code: "fixture-portal-b", name: "Fixture Portal B", kind: "fixture", pollIntervalMinutes: 60 },
  });

  // --- Agencies + users + territories -------------------------------------
  const password = hashPassword("demo1234");

  const agencyDefs = [
    {
      name: "Immo Vandenberghe", slug: "immo-vandenberghe", minAlertScore: 85,
      territories: [
        { kind: "POSTAL_CODE" as const, value: "9000", label: "9000 Gent" },
        { kind: "POSTAL_CODE" as const, value: "9030", label: "9030 Mariakerke" },
        { kind: "POSTAL_CODE" as const, value: "9040", label: "9040 Sint-Amandsberg" },
        { kind: "POSTAL_CODE" as const, value: "9050", label: "9050 Gentbrugge" },
        { kind: "MUNICIPALITY" as const, value: "gent", label: "Gent (gemeente)" },
      ],
      users: [
        { firstName: "An", lastName: "Vandenberghe", role: "AGENCY_ADMIN" as const },
        { firstName: "Thomas", lastName: "Peeters", role: "AGENT" as const },
        { firstName: "Sofie", lastName: "Martens", role: "AGENT" as const },
      ],
      cities: GENT_CITIES,
    },
    {
      name: "Kust & Co Vastgoed", slug: "kust-co", minAlertScore: 85,
      territories: [
        { kind: "POSTAL_CODE" as const, value: "8000", label: "8000 Brugge" },
        { kind: "POSTAL_CODE" as const, value: "8400", label: "8400 Oostende" },
        { kind: "MUNICIPALITY" as const, value: "brugge", label: "Brugge" },
        { kind: "MUNICIPALITY" as const, value: "oostende", label: "Oostende" },
        { kind: "PROVINCE" as const, value: "west-vlaanderen", label: "West-Vlaanderen" },
      ],
      users: [
        { firstName: "Bart", lastName: "Declerck", role: "AGENCY_ADMIN" as const },
        { firstName: "Eva", lastName: "Willems", role: "AGENT" as const },
        { firstName: "Koen", lastName: "Maes", role: "AGENT" as const },
      ],
      cities: [OTHER_CITIES[0]!, OTHER_CITIES[1]!],
    },
    {
      name: "Antwerp City Estates", slug: "antwerp-city", minAlertScore: 80,
      territories: [
        { kind: "POSTAL_CODE" as const, value: "2000", label: "2000 Antwerpen" },
        { kind: "POSTAL_CODE" as const, value: "2018", label: "2018 Antwerpen" },
        { kind: "POSTAL_CODE" as const, value: "2600", label: "2600 Berchem" },
        { kind: "MUNICIPALITY" as const, value: "antwerpen", label: "Antwerpen" },
      ],
      users: [
        { firstName: "Lien", lastName: "Jacobs", role: "AGENCY_ADMIN" as const },
        { firstName: "Stijn", lastName: "Wouters", role: "AGENT" as const },
        { firstName: "Nele", lastName: "Claes", role: "AGENT" as const },
      ],
      cities: [OTHER_CITIES[2]!, OTHER_CITIES[3]!, OTHER_CITIES[4]!],
    },
    {
      name: "Leuven Wonen", slug: "leuven-wonen", minAlertScore: 85,
      territories: [
        { kind: "POSTAL_CODE" as const, value: "3000", label: "3000 Leuven" },
        { kind: "POSTAL_CODE" as const, value: "3001", label: "3001 Heverlee" },
        { kind: "POSTAL_CODE" as const, value: "3010", label: "3010 Kessel-Lo" },
        { kind: "MUNICIPALITY" as const, value: "leuven", label: "Leuven" },
      ],
      users: [
        { firstName: "Geert", lastName: "Hermans", role: "AGENCY_ADMIN" as const },
        { firstName: "Katrien", lastName: "Segers", role: "AGENT" as const },
        { firstName: "Tom", lastName: "Pauwels", role: "AGENT" as const },
      ],
      cities: [OTHER_CITIES[5]!, OTHER_CITIES[6]!],
    },
    {
      name: "Limburg Immo Groep", slug: "limburg-immo", minAlertScore: 85,
      territories: [
        { kind: "POSTAL_CODE" as const, value: "3500", label: "3500 Hasselt" },
        { kind: "POSTAL_CODE" as const, value: "3600", label: "3600 Genk" },
        { kind: "MUNICIPALITY" as const, value: "hasselt", label: "Hasselt" },
        { kind: "MUNICIPALITY" as const, value: "genk", label: "Genk" },
        { kind: "PROVINCE" as const, value: "limburg", label: "Limburg" },
      ],
      users: [
        { firstName: "Ilse", lastName: "Lemmens", role: "AGENCY_ADMIN" as const },
        { firstName: "Dirk", lastName: "Aerts", role: "AGENT" as const },
      ],
      cities: [OTHER_CITIES[7]!, OTHER_CITIES[8]!],
    },
  ];

  await prisma.user.create({
    data: {
      email: "admin@immoradar.be",
      passwordHash: password,
      firstName: "Platform",
      lastName: "Admin",
      role: "PLATFORM_ADMIN",
    },
  });

  const agencies: { id: string; slug: string; users: { id: string; firstName: string; role: string }[]; cities: City[] }[] = [];
  for (const def of agencyDefs) {
    const agency = await prisma.agency.create({
      data: {
        name: def.name,
        slug: def.slug,
        minAlertScore: def.minAlertScore,
        territories: { create: def.territories },
      },
    });
    const users = [];
    for (const u of def.users) {
      const user = await prisma.user.create({
        data: {
          agencyId: agency.id,
          email: `${u.firstName.toLowerCase()}@${def.slug}.be`,
          passwordHash: password,
          firstName: u.firstName,
          lastName: u.lastName,
          role: u.role,
        },
      });
      users.push({ id: user.id, firstName: user.firstName, role: user.role });
    }
    agencies.push({ id: agency.id, slug: def.slug, users, cities: def.cities });
  }
  const hero = agencies[0]!; // Immo Vandenberghe (Gent)
  const thomas = hero.users.find((u) => u.firstName === "Thomas")!;

  console.log(`Created ${agencies.length} agencies, ${agencies.reduce((n, a) => n + a.users.length, 0) + 1} users`);

  // --- CRM contacts --------------------------------------------------------
  // Scenario contacts first (hero agency)
  const pieter = await prisma.crmContact.create({
    data: {
      agencyId: hero.id,
      externalContactId: "IV-2019-0412",
      firstName: "Pieter",
      lastName: "Janssens",
      normalizedName: "janssens pieter",
      email: "pieter.janssens@telenet.be",
      normalizedEmail: "pieter.janssens@telenet.be",
      phone: "0472 12 34 56",
      normalizedPhone: "+32472123456",
      address: "Zandberg 8",
      postalCode: "9000",
      city: "gent",
      assignedAgentId: thomas.id,
      assignedAgentName: "Thomas Peeters",
      contactType: "BUYER",
      status: "WON",
      sourceCreatedAt: new Date("2019-06-12"),
      lastContactAt: daysAgo(120),
      notes: "Kocht rijwoning via ons in 2019. Zeer tevreden, sprak toen over 'ooit groter kopen'.",
      interactions: {
        create: [
          { kind: "VISIT", occurredAt: new Date("2019-05-20"), summary: "Bezoek rijwoning Zandberg" },
          { kind: "CALL", occurredAt: daysAgo(120), summary: "Tevredenheidscheck; gezin groeit" },
        ],
      },
    },
  });

  // Scenario D: dormant valuation lead, relationship score high, no market signal
  await prisma.crmContact.create({
    data: {
      agencyId: hero.id,
      externalContactId: "IV-2024-0783",
      firstName: "An",
      lastName: "De Clercq",
      normalizedName: "an clercq de",
      email: "an.declercq@skynet.be",
      normalizedEmail: "an.declercq@skynet.be",
      phone: "0486 44 55 66",
      normalizedPhone: "+32486445566",
      address: "Kortrijksesteenweg 214",
      postalCode: "9000",
      city: "gent",
      assignedAgentId: thomas.id,
      assignedAgentName: "Thomas Peeters",
      contactType: "VALUATION_LEAD",
      status: "DORMANT",
      sourceCreatedAt: new Date("2024-10-05"),
      lastContactAt: new Date("2024-11-10"),
      notes: "Vroeg schatting aan voor woning; geen mandaat gevolgd.",
      interactions: {
        create: [
          { kind: "VALUATION", occurredAt: new Date("2024-10-20"), summary: "Schatting uitgevoerd: €520.000" },
        ],
      },
    },
  });

  // Bulk contacts across all agencies (~500 total)
  const contactTypeWeights = [
    ["BUYER", 0.24], ["SELLER", 0.16], ["VALUATION_LEAD", 0.14], ["PROSPECT", 0.16],
    ["FORMER_CLIENT", 0.1], ["LANDLORD", 0.08], ["TENANT", 0.06], ["UNKNOWN", 0.06],
  ] as const;
  function weightedType(): string {
    const r = rand();
    let acc = 0;
    for (const [type, w] of contactTypeWeights) {
      acc += w;
      if (r <= acc) return type;
    }
    return "UNKNOWN";
  }

  let contactCount = 2;
  const usedPhones = new Set<string>(["+32472123456", "+32486445566"]);
  for (const agency of agencies) {
    const perAgency = agency.id === hero.id ? 148 : 87 + randInt(0, 3);
    for (let i = 0; i < perAgency; i++) {
      const firstName = pick(FIRST_NAMES);
      const lastName = pick(LAST_NAMES);
      const cityDef = pick(agency.cities);
      let phone: string | null = null;
      if (chance(0.85)) {
        do {
          phone = `+324${randInt(70, 99)}${String(randInt(100000, 999999)).padStart(6, "0")}`;
        } while (usedPhones.has(phone));
        usedPhones.add(phone);
      }
      const email = chance(0.8)
        ? `${firstName.toLowerCase()}.${lastName.toLowerCase().replace(/\s+/g, "")}${randInt(1, 99)}@telenet.be`
        : null;
      const contactType = weightedType();
      const createdYearsAgo = randInt(0, 8);
      const sourceCreatedAt = daysAgo(createdYearsAgo * 365 + randInt(0, 300));
      const lastContactAt = chance(0.8) ? daysAgo(randInt(5, 900)) : null;
      const status =
        contactType === "SELLER"
          ? pick(["LOST", "WON", "ACTIVE", "DORMANT"] as const)
          : contactType === "BUYER"
            ? pick(["WON", "ACTIVE", "DORMANT"] as const)
            : pick(["ACTIVE", "DORMANT", "LOST", "UNKNOWN"] as const);

      const normalizedName = [firstName, ...lastName.split(" ")]
        .map((t) => t.toLowerCase())
        .sort()
        .join(" ");

      await prisma.crmContact.create({
        data: {
          agencyId: agency.id,
          externalContactId: `${agency.slug.toUpperCase().slice(0, 2)}-${1000 + i}`,
          firstName,
          lastName,
          normalizedName,
          email,
          normalizedEmail: email,
          phone,
          normalizedPhone: phone,
          postalCode: cityDef.postalCode,
          city: cityDef.city.toLowerCase(),
          assignedAgentId: chance(0.7) ? pick(agency.users.filter((u) => u.role === "AGENT")).id : null,
          contactType: contactType as Prisma.CrmContactUncheckedCreateInput["contactType"],
          status: status as Prisma.CrmContactUncheckedCreateInput["status"],
          sourceCreatedAt,
          lastContactAt,
        },
      });
      contactCount++;
    }
  }
  console.log(`Created ${contactCount} CRM contacts`);

  // --- Market data through the real ingestion pipeline ---------------------
  const ingestion = new IngestionService(prisma);
  const sourceIds = { a: portalA.id, b: portalB.id };

  interface TimelineStep { day: number; price: number }
  interface History {
    source: "a" | "b";
    idBase: string;
    city: City;
    street: string;
    houseNumber: string;
    surface: number;
    bedrooms: number;
    propertyType: string;
    isPrivate: boolean;
    sellerName: string;
    sellerPhone: string | null;
    agencyName: string | null;
    steps: TimelineStep[];
    removedAtDay: number | null; // day the listing disappeared
    relistAtDay: number | null; // relisted (new listing id) at this day
    relistPrice?: number;
    dualListed: boolean; // also on the other portal
  }

  const histories: History[] = [];
  let histIdx = 0;
  const usedAddresses = new Set<string>();

  function makeHistory(city: City, opts: Partial<History> = {}): History {
    let street: string, houseNumber: string, key: string;
    do {
      street = pick(STREETS);
      houseNumber = String(randInt(1, 180));
      key = `${city.postalCode}|${street}|${houseNumber}`;
    } while (usedAddresses.has(key));
    usedAddresses.add(key);

    const isPrivate = opts.isPrivate ?? chance(0.45);
    const basePrice = randInt(22, 78) * 10000;
    const startDay = randInt(10, 100);
    const steps: TimelineStep[] = [{ day: startDay, price: basePrice }];
    const dropCount = chance(0.35) ? randInt(1, 2) : 0;
    let price = basePrice;
    for (let d = 0; d < dropCount; d++) {
      const dropDay = Math.max(2, startDay - randInt(15, 30) * (d + 1));
      if (dropDay >= (steps[steps.length - 1]?.day ?? 0)) continue;
      price = Math.round((price * (1 - randInt(3, 8) / 100)) / 1000) * 1000;
      steps.push({ day: dropDay, price });
    }

    return {
      source: chance(0.6) ? "a" : "b",
      idBase: `SEED-${++histIdx}`,
      city,
      street,
      houseNumber,
      surface: randInt(70, 260),
      bedrooms: randInt(1, 5),
      propertyType: pick(["woning", "woning", "appartement", "villa"]),
      isPrivate,
      sellerName: `${pick(FIRST_NAMES)} ${pick(LAST_NAMES)}`,
      sellerPhone: isPrivate ? `+324${randInt(70, 99)}${String(randInt(100000, 999999)).padStart(6, "0")}` : null,
      agencyName: isPrivate ? null : pick(AGENCY_NAMES),
      steps,
      removedAtDay: null,
      relistAtDay: null,
      dualListed: chance(0.5),
      ...opts,
    };
  }

  /** Price that applied on a given (backdated) day of a history's timeline. */
  function priceAt(h: History, day: number): number {
    // Steps have descending `day` (older first); the applicable price is the
    // most recent step at or before that moment, i.e. smallest step.day >= day.
    const applicable = [...h.steps].sort((a, b) => b.day - a.day).filter((s) => s.day >= day);
    return applicable.length > 0 ? applicable[applicable.length - 1]!.price : h.steps[0]!.price;
  }

  // ~150 generated histories over demo cities (weighted toward Gent)
  for (let i = 0; i < 150; i++) {
    const city = chance(0.4) ? pick(GENT_CITIES) : pick(ALL_CITIES);
    const history = makeHistory(city);
    // ~15% get removed; half of those relist
    if (chance(0.15)) {
      const lastStep = history.steps[history.steps.length - 1]!;
      history.removedAtDay = Math.max(1, lastStep.day - randInt(5, 20));
      if (chance(0.5) && history.removedAtDay > 4) {
        history.relistAtDay = Math.max(1, history.removedAtDay - randInt(2, 10));
        history.relistPrice = Math.round((lastStep.price * 0.97) / 1000) * 1000;
      }
    }
    histories.push(history);
  }

  // Scenario C: private seller, 67 days online, 2 price drops (Gent 9000)
  histories.push(
    makeHistory(GENT_CITIES[0]!, {
      idBase: "SCEN-C",
      source: "a",
      isPrivate: true,
      sellerName: "Karel Vermeulen",
      sellerPhone: "+32478551289",
      steps: [
        { day: 67, price: 489000 },
        { day: 40, price: 469000 },
        { day: 8, price: 449000 },
      ],
    }),
  );

  // Scenario E: relisted property with previous CRM relationship (Gent 9000)
  const scenarioE = makeHistory(GENT_CITIES[0]!, {
    idBase: "SCEN-E",
    source: "a",
    isPrivate: true,
    sellerName: "Els Van Damme",
    sellerPhone: "+32475661234",
    steps: [{ day: 85, price: 549000 }],
    removedAtDay: 32,
    relistAtDay: 3,
    relistPrice: 529000,
  });
  histories.push(scenarioE);

  // Run timelines through the ingestion pipeline, oldest step first
  interface IngestOp { day: number; history: History; price: number; listingSuffix: string }
  const ops: IngestOp[] = [];
  for (const h of histories) {
    const startDay = h.steps[0]!.day;
    const endDay = h.removedAtDay ?? randInt(0, 4);
    // Observation days: every price-change step plus periodic refresh polls,
    // so each listing accumulates a realistic snapshot history.
    const observedDays = new Set<number>(h.steps.map((s) => s.day));
    for (let d = startDay - randInt(5, 9); d > endDay; d -= randInt(7, 14)) {
      observedDays.add(d);
    }
    for (const day of observedDays) {
      if (day < endDay) continue;
      ops.push({ day, history: h, price: priceAt(h, day), listingSuffix: "" });
      if (h.dualListed) {
        ops.push({ day: Math.max(0, day - 1), history: h, price: priceAt(h, day), listingSuffix: "-B" });
      }
    }
    if (h.relistAtDay) {
      const relistPrice = h.relistPrice ?? h.steps[0]!.price;
      ops.push({ day: h.relistAtDay, history: h, price: relistPrice, listingSuffix: "-RELIST" });
      if (h.relistAtDay > 1) {
        ops.push({ day: randInt(0, h.relistAtDay - 1), history: h, price: relistPrice, listingSuffix: "-RELIST" });
      }
    }
  }
  ops.sort((a, b) => b.day - a.day);

  function rawListingFor(op: IngestOp): RawListing {
    const h = op.history;
    const isRelist = op.listingSuffix === "-RELIST";
    const onPortalB = op.listingSuffix === "-B" ? h.source === "a" : h.source === "b";
    return {
      source: onPortalB ? "fixture-portal-b" : "fixture-portal-a",
      sourceListingId: `${h.idBase}${op.listingSuffix}`,
      sourceUrl: `https://portal-${onPortalB ? "b" : "a"}.example/listing/${h.idBase}${op.listingSuffix}`,
      listingType: "sale",
      title: `${h.propertyType === "appartement" ? "Appartement" : "Woning"} te koop — ${h.city.city}`,
      description: h.isPrivate ? pick(PRIVATE_DESCRIPTIONS) : pick(PRO_DESCRIPTIONS),
      price: op.price,
      street: h.street,
      houseNumber: h.houseNumber,
      postalCode: h.city.postalCode,
      city: h.city.city,
      surfaceArea: h.surface,
      bedrooms: h.bedrooms,
      propertyType: h.propertyType,
      sellerName: isRelist ? h.sellerName : h.sellerName,
      sellerPhone: h.sellerPhone ?? undefined,
      sellerKind: h.isPrivate ? "particulier" : "agency",
      sellerListingCount: h.isPrivate ? 1 : randInt(8, 40),
      agencyName: h.agencyName ?? undefined,
    };
  }

  let snapshotOps = 0;
  for (const op of ops) {
    const h = op.history;
    // Skip steps after the listing was removed (relist handled separately)
    if (op.listingSuffix !== "-RELIST" && h.removedAtDay !== null && op.day < h.removedAtDay) continue;
    const at = daysAgo(op.day);
    const raw = rawListingFor(op);
    const sourceId = raw.source === "fixture-portal-b" ? sourceIds.b : sourceIds.a;
    await ingestion.ingestListing(sourceId, normalizeListing(raw), at);
    snapshotOps++;
  }

  // Mark removed listings as REMOVED with a LISTING_REMOVED event (history
  // fabrication: the confirmation logic itself is unit-tested)
  for (const h of histories) {
    if (h.removedAtDay === null) continue;
    const listing = await prisma.listing.findFirst({
      where: { sourceListingId: h.idBase },
      select: { id: true, status: true },
    });
    if (!listing) continue;
    const removedAt = daysAgo(h.removedAtDay);
    await prisma.listing.update({
      where: { id: listing.id },
      data: { status: "REMOVED", lastSeenAt: removedAt, missingSince: removedAt },
    });
    await prisma.listingEvent.create({
      data: {
        listingId: listing.id,
        type: "LISTING_REMOVED",
        occurredAt: removedAt,
        payload: { missingSince: removedAt.toISOString(), confirmedAfterRuns: 2 },
      },
    });
  }

  // Relists were ingested before removal marking could interfere; re-run relist
  // ingestion now that the original listings are REMOVED so RELISTED events fire.
  for (const h of histories) {
    if (!h.relistAtDay) continue;
    const relistListing = await prisma.listing.findFirst({
      where: { sourceListingId: `${h.idBase}-RELIST` },
      include: { events: { select: { type: true } } },
    });
    if (!relistListing) continue;
    if (!relistListing.events.some((e) => e.type === "RELISTED")) {
      await prisma.listingEvent.create({
        data: {
          listingId: relistListing.id,
          type: "RELISTED",
          occurredAt: daysAgo(h.relistAtDay),
          payload: {
            previousRemovedAt: daysAgo(h.removedAtDay ?? h.relistAtDay + 20).toISOString(),
            daysOffMarket: (h.removedAtDay ?? 0) - h.relistAtDay,
          },
        },
      });
    }
  }

  // Scenario B: fresh FSBO in Gent matching Pieter Janssens (previous buyer)
  await ingestion.ingestListing(
    sourceIds.a,
    normalizeListing({
      source: "fixture-portal-a",
      sourceListingId: "SCEN-B",
      sourceUrl: "https://portal-a.example/listing/SCEN-B",
      listingType: "sale",
      title: "Ruime stadswoning met tuin — Gent centrum",
      description: "Verkoop door particulier, zonder makelaar. Ruime stadswoning met zuidgerichte tuin.",
      price: 625000,
      street: "Lange Violettestraat",
      houseNumber: "88",
      postalCode: "9000",
      city: "Gent",
      surfaceArea: 210,
      bedrooms: 4,
      propertyType: "woning",
      sellerName: "Pieter Janssens",
      sellerPhone: "0472 12 34 56",
      sellerKind: "particulier",
      sellerListingCount: 1,
    }),
    new Date(NOW.getTime() - 12 * 60_000), // detected 12 minutes ago
  );

  // Scenario A: fresh FSBO in Mariakerke with NO CRM relationship
  await ingestion.ingestListing(
    sourceIds.a,
    normalizeListing({
      source: "fixture-portal-a",
      sourceListingId: "SCEN-A",
      sourceUrl: "https://portal-a.example/listing/SCEN-A",
      listingType: "sale",
      title: "Halfopen bebouwing met garage — Mariakerke",
      description: "Rechtstreeks van eigenaar, geen makelaar. Halfopen bebouwing, rustige wijk.",
      price: 425000,
      street: "Eeklostraat",
      houseNumber: "51",
      postalCode: "9030",
      city: "Mariakerke",
      surfaceArea: 165,
      bedrooms: 3,
      propertyType: "woning",
      sellerName: "Jonas Verstraete",
      sellerPhone: "0499 88 77 11",
      sellerKind: "particulier",
      sellerListingCount: 1,
    }),
    new Date(NOW.getTime() - 45 * 60_000),
  );

  const counts = {
    properties: await prisma.property.count(),
    listings: await prisma.listing.count(),
    snapshots: await prisma.listingSnapshot.count(),
    events: await prisma.listingEvent.count(),
  };
  console.log(`Market data: ${counts.properties} properties, ${counts.listings} listings, ${counts.snapshots} snapshots, ${counts.events} events (${snapshotOps} ingestion ops)`);

  // Scenario E CRM link: contact with a relationship to the relisted property
  const scenarioEListing = await prisma.listing.findFirst({
    where: { sourceListingId: "SCEN-E-RELIST" },
    select: { propertyId: true },
  });
  if (scenarioEListing?.propertyId) {
    const elsContact = await prisma.crmContact.create({
      data: {
        agencyId: hero.id,
        externalContactId: "IV-2021-0233",
        firstName: "Els",
        lastName: "Van Damme",
        normalizedName: "damme els van",
        phone: "0475 66 12 34",
        normalizedPhone: "+32475661234",
        postalCode: "9000",
        city: "gent",
        assignedAgentId: thomas.id,
        assignedAgentName: "Thomas Peeters",
        contactType: "VALUATION_LEAD",
        status: "LOST",
        sourceCreatedAt: new Date("2021-04-15"),
        lastContactAt: daysAgo(400),
        notes: "Vroeg in 2021 schatting; koos toen om zelf te verkopen.",
      },
    });
    await prisma.contactPropertyRelationship.create({
      data: {
        contactId: elsContact.id,
        propertyId: scenarioEListing.propertyId,
        kind: "VALUATION_REQUESTED",
        since: new Date("2021-04-20"),
      },
    });
  }

  // Pieter's 2019 purchase: property relationship for the intelligence graph
  const pieterHome = await prisma.property.create({
    data: {
      address: "zandberg 8, 9000 gent",
      street: "zandberg",
      houseNumber: "8",
      postalCode: "9000",
      city: "gent",
      province: "oost-vlaanderen",
      propertyType: "HOUSE",
      bedrooms: 3,
      surfaceArea: 140,
    },
  });
  await prisma.contactPropertyRelationship.create({
    data: { contactId: pieter.id, propertyId: pieterHome.id, kind: "BOUGHT", since: new Date("2019-06-12") },
  });

  // --- Intelligence: opportunities, LeadRevive, alerts ---------------------
  const opportunityService = new OpportunityService(prisma);
  const leadRevive = new LeadReviveService(prisma);
  const alertService = new AlertService(prisma);
  const digest = new DigestService(prisma);

  for (const agency of agencies) {
    const gen = await opportunityService.generateForAgency(agency.id);
    const revive = await leadRevive.scanAgency(agency.id);
    console.log(`${agency.slug}: ${gen.created} market opportunities (${gen.crossMatches} CRM matches), ${revive.created} dormant leads`);
  }

  // --- Workflow history so pipeline & analytics have depth -----------------
  const workflow = new WorkflowService(prisma);
  for (const agency of agencies) {
    const agents = agency.users.filter((u) => u.role === "AGENT");
    if (agents.length === 0) continue;
    const admin = agency.users.find((u) => u.role === "AGENCY_ADMIN") ?? agents[0]!;
    const opps = await prisma.opportunity.findMany({
      where: { agencyId: agency.id, status: "NEW" },
      orderBy: { detectedAt: "asc" },
      take: 40,
      select: { id: true, listingId: true },
    });
    let i = 0;
    for (const opp of opps) {
      // Leave the freshest ~40% untouched in NEW
      if (i++ % 5 < 2) continue;
      // Never touch the flagship scenario listings
      const agent = pick(agents);
      try {
        await workflow.assign(agency.id, opp.id, agent.id, admin.id);
        const path = rand();
        if (path < 0.35) {
          await workflow.changeStatus(agency.id, opp.id, "CONTACTED", agent.id);
        } else if (path < 0.55) {
          await workflow.changeStatus(agency.id, opp.id, "CONTACTED", agent.id);
          await workflow.changeStatus(agency.id, opp.id, "INTERESTED", agent.id);
          await workflow.changeStatus(agency.id, opp.id, "VALUATION_BOOKED", agent.id);
          if (path < 0.45) {
            await workflow.changeStatus(agency.id, opp.id, "MANDATE_PROPOSED", agent.id);
            await workflow.changeStatus(
              agency.id, opp.id, path < 0.4 ? "MANDATE_WON" : "LOST", agent.id,
            );
          }
        } else if (path < 0.65) {
          await workflow.changeStatus(agency.id, opp.id, "CONTACTED", agent.id);
          await workflow.changeStatus(agency.id, opp.id, "LOST", agent.id, "Eigenaar verkoopt toch zelf");
        } else if (path < 0.72) {
          await workflow.changeStatus(agency.id, opp.id, "DISMISSED", admin.id, "Buiten focus");
        }
      } catch {
        // Transitions can legitimately conflict; ignore in seed
      }
    }
  }

  // --- Alerts + digest -----------------------------------------------------
  for (const agency of agencies) {
    await alertService.dispatchInstantAlerts(agency.id);
  }
  await digest.sendMorningBrief(hero.id);

  const oppCount = await prisma.opportunity.count();
  const alertCount = await prisma.alert.count();
  console.log(`Total: ${oppCount} opportunities, ${alertCount} alerts`);

  // --- Verify flagship scenarios ------------------------------------------
  const scenarioB = await prisma.opportunity.findFirst({
    where: { agencyId: hero.id, listing: { sourceListingId: "SCEN-B" } },
    include: { scores: { orderBy: { computedAt: "desc" }, take: 1 }, contact: { select: { lastName: true } } },
  });
  console.log(
    `Scenario B (CRM + FSBO): score=${scenarioB?.scores[0]?.total ?? "?"} contact=${scenarioB?.contact?.lastName ?? "NONE"} origin=${scenarioB?.origin ?? "?"}`,
  );

  console.log("\nDemo login: thomas@immo-vandenberghe.be / demo1234");
  console.log("Platform admin: admin@immoradar.be / demo1234");
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
