import PDFDocument from "pdfkit";

export type ActivityType = "coloring" | "maze" | "wordsearch";

interface GenerateOptions {
  activityType: ActivityType;
  theme: string;
}

export function generatePdf(options: GenerateOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header with Islamic styling
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#d4a843")
      .text("Bismillah", { align: "center" });
    doc.moveDown(0.3);
    doc
      .fontSize(26)
      .font("Helvetica-Bold")
      .fillColor("#0d9488")
      .text("Noor Printables", { align: "center" });
    doc.moveDown(0.3);
    doc
      .fontSize(12)
      .font("Helvetica")
      .fillColor("#666666")
      .text(`Theme: ${options.theme}`, { align: "center" });
    doc.moveDown(0.2);
    doc
      .fontSize(10)
      .fillColor("#999999")
      .text(`${getActivityLabel(options.activityType)} | Ages 4-8`, {
        align: "center",
      });
    doc.moveDown(1);
    doc.fillColor("#000000");

    // Decorative line with star
    const lineY = doc.y;
    doc.strokeColor("#d4a843").lineWidth(1);
    doc.moveTo(50, lineY).lineTo(250, lineY).stroke();
    drawStar(doc, 297.5, lineY, 8, 4, 8, "#d4a843");
    doc.moveTo(345, lineY).lineTo(545, lineY).stroke();
    doc.moveDown(1);

    switch (options.activityType) {
      case "coloring":
        drawColoringPage(doc, options.theme);
        break;
      case "maze":
        drawMaze(doc, options.theme);
        break;
      case "wordsearch":
        drawWordSearch(doc, options.theme);
        break;
    }

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor("#aaaaaa")
      .text("Generated by Noor Printables - Islamic educational printables for kids", { align: "center" });

    doc.end();
  });
}

function getActivityLabel(type: ActivityType): string {
  const labels: Record<ActivityType, string> = {
    coloring: "Coloring Page",
    maze: "Maze",
    wordsearch: "Word Search",
  };
  return labels[type];
}

// ── Coloring Page ──────────────────────────────────────────────

function drawColoringPage(doc: PDFKit.PDFDocument, theme: string) {
  doc
    .fontSize(18)
    .font("Helvetica-Bold")
    .fillColor("#333333")
    .text(`Color this: ${theme}`, { align: "center" });
  doc.moveDown(1);

  const cx = 297.5;
  const cy = 430;

  doc.strokeColor("#333333").lineWidth(2);

  // Islamic geometric pattern - 8-pointed star (Rub el Hizb style)
  draw8PointStar(doc, cx, cy, 110, 55);

  // Crescent moon on top
  drawCrescent(doc, cx, cy - 160, 30);

  // Inner decorative circles (Islamic rosette)
  for (let i = 0; i < 8; i++) {
    const angle = (i * Math.PI * 2) / 8;
    const px = cx + Math.cos(angle) * 55;
    const py = cy + Math.sin(angle) * 55;
    doc.circle(px, py, 15).stroke();
  }

  // Outer decoration ring of small stars
  for (let i = 0; i < 12; i++) {
    const angle = (i * Math.PI * 2) / 12;
    const sx = cx + Math.cos(angle) * 145;
    const sy = cy + Math.sin(angle) * 145;
    drawStar(doc, sx, sy, 10, 5, 5, "#333333");
  }

  // Arch shapes (mihrab-inspired) at cardinal points
  for (let i = 0; i < 4; i++) {
    const angle = (i * Math.PI * 2) / 4 - Math.PI / 2;
    const ax = cx + Math.cos(angle) * 125;
    const ay = cy + Math.sin(angle) * 125;
    doc.circle(ax, ay, 12).stroke();
    doc.circle(ax, ay, 6).stroke();
  }

  // Border frame
  doc.strokeColor("#333333").lineWidth(1.5);
  const margin = 60;
  doc.rect(margin, cy - 190, 595 - margin * 2, 380).stroke();

  // Corner ornaments
  const corners = [
    [margin, cy - 190],
    [595 - margin, cy - 190],
    [margin, cy + 190],
    [595 - margin, cy + 190],
  ];
  for (const [cx2, cy2] of corners) {
    doc.circle(cx2, cy2, 8).stroke();
    doc.circle(cx2, cy2, 3).stroke();
  }

  doc.moveDown(18);
  doc
    .fontSize(13)
    .font("Helvetica")
    .fillColor("#666666")
    .text(`Color this beautiful ${theme}-themed Islamic pattern!`, { align: "center" });
  doc.moveDown(0.3);
  doc
    .fontSize(10)
    .fillColor("#999999")
    .text("Name: _______________________    Date: _______________", {
      align: "center",
    });
}

function draw8PointStar(
  doc: PDFKit.PDFDocument,
  cx: number,
  cy: number,
  outerR: number,
  innerR: number
) {
  const points = 8;
  const step = Math.PI / points;

  const coords: { x: number; y: number }[] = [];
  for (let i = 0; i < 2 * points; i++) {
    const r = i % 2 === 0 ? outerR : innerR;
    const angle = i * step - Math.PI / 2;
    coords.push({
      x: cx + Math.cos(angle) * r,
      y: cy + Math.sin(angle) * r,
    });
  }

  doc.moveTo(coords[0].x, coords[0].y);
  for (let i = 1; i < coords.length; i++) {
    doc.lineTo(coords[i].x, coords[i].y);
  }
  doc.lineTo(coords[0].x, coords[0].y);
  doc.stroke();

  // Inner star rotated
  const coords2: { x: number; y: number }[] = [];
  for (let i = 0; i < 2 * points; i++) {
    const r = i % 2 === 0 ? outerR * 0.7 : innerR * 0.7;
    const angle = i * step - Math.PI / 2 + step / 2;
    coords2.push({
      x: cx + Math.cos(angle) * r,
      y: cy + Math.sin(angle) * r,
    });
  }

  doc.moveTo(coords2[0].x, coords2[0].y);
  for (let i = 1; i < coords2.length; i++) {
    doc.lineTo(coords2[i].x, coords2[i].y);
  }
  doc.lineTo(coords2[0].x, coords2[0].y);
  doc.stroke();
}

function drawCrescent(
  doc: PDFKit.PDFDocument,
  cx: number,
  cy: number,
  r: number
) {
  // Outer circle
  doc.circle(cx, cy, r).stroke();
  // Inner circle offset to create crescent
  doc.save();
  doc.circle(cx + r * 0.35, cy - r * 0.1, r * 0.8).stroke();
  doc.restore();

  // Small star next to crescent
  drawStar(doc, cx + r * 1.5, cy - r * 0.3, 6, 3, 5, "#333333");
}

// ── Maze ───────────────────────────────────────────────────────

function drawMaze(doc: PDFKit.PDFDocument, theme: string) {
  doc
    .fontSize(18)
    .font("Helvetica-Bold")
    .fillColor("#333333")
    .text(`Maze: ${theme}`, { align: "center" });
  doc.moveDown(0.5);
  doc
    .fontSize(11)
    .font("Helvetica")
    .fillColor("#666666")
    .text("Help find the path! Follow the road from START to the MOSQUE.", {
      align: "center",
    });
  doc.moveDown(1);

  const startX = 75;
  const startY = 260;
  const cellSize = 30;
  const cols = 15;
  const rows = 15;

  const maze = generateMazeGrid(cols, rows);

  doc.strokeColor("#333333").lineWidth(1.5);

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const x = startX + c * cellSize;
      const y = startY + r * cellSize;
      const cell = maze[r][c];

      if (cell.top) {
        doc.moveTo(x, y).lineTo(x + cellSize, y).stroke();
      }
      if (cell.right) {
        doc.moveTo(x + cellSize, y).lineTo(x + cellSize, y + cellSize).stroke();
      }
      if (cell.bottom) {
        doc.moveTo(x, y + cellSize).lineTo(x + cellSize, y + cellSize).stroke();
      }
      if (cell.left) {
        doc.moveTo(x, y).lineTo(x, y + cellSize).stroke();
      }
    }
  }

  // START label with crescent
  doc
    .fontSize(9)
    .font("Helvetica-Bold")
    .fillColor("#0d9488")
    .text("START", startX, startY - 20, { width: cellSize * 2 });

  // MOSQUE (finish) label
  const finishX = startX + (cols - 2) * cellSize;
  const finishY = startY + rows * cellSize + 5;
  doc
    .fillColor("#d4a843")
    .text("MOSQUE", finishX - 10, finishY, { width: cellSize * 3 });

  // Draw small mosque icon near finish
  const mx = finishX + cellSize * 0.5;
  const my = finishY + 20;
  doc.strokeColor("#d4a843").lineWidth(1);
  // Dome
  doc
    .moveTo(mx - 12, my)
    .quadraticCurveTo(mx, my - 15, mx + 12, my)
    .stroke();
  // Base
  doc.rect(mx - 12, my, 24, 12).stroke();
  // Minaret
  doc.rect(mx + 14, my - 8, 4, 20).stroke();

  doc
    .fontSize(10)
    .fillColor("#999999")
    .text(
      "Name: _______________________",
      50,
      startY + rows * cellSize + 55,
      { width: 495, align: "center" }
    );
}

interface MazeCell {
  top: boolean;
  right: boolean;
  bottom: boolean;
  left: boolean;
  visited: boolean;
}

function generateMazeGrid(cols: number, rows: number): MazeCell[][] {
  const grid: MazeCell[][] = [];
  for (let r = 0; r < rows; r++) {
    grid[r] = [];
    for (let c = 0; c < cols; c++) {
      grid[r][c] = {
        top: true,
        right: true,
        bottom: true,
        left: true,
        visited: false,
      };
    }
  }

  let seed = Date.now() % 10000;
  function random() {
    seed = (seed * 16807 + 0) % 2147483647;
    return (seed - 1) / 2147483646;
  }

  const stack: [number, number][] = [];
  let current: [number, number] = [0, 0];
  grid[0][0].visited = true;
  stack.push(current);

  while (stack.length > 0) {
    const [cr, cc] = current;
    const neighbors: [number, number, string, string][] = [];

    if (cr > 0 && !grid[cr - 1][cc].visited)
      neighbors.push([cr - 1, cc, "top", "bottom"]);
    if (cr < rows - 1 && !grid[cr + 1][cc].visited)
      neighbors.push([cr + 1, cc, "bottom", "top"]);
    if (cc > 0 && !grid[cr][cc - 1].visited)
      neighbors.push([cr, cc - 1, "left", "right"]);
    if (cc < cols - 1 && !grid[cr][cc + 1].visited)
      neighbors.push([cr, cc + 1, "right", "left"]);

    if (neighbors.length > 0) {
      const idx = Math.floor(random() * neighbors.length);
      const [nr, nc, wall1, wall2] = neighbors[idx];

      (grid[cr][cc] as unknown as Record<string, boolean>)[wall1] = false;
      (grid[nr][nc] as unknown as Record<string, boolean>)[wall2] = false;

      grid[nr][nc].visited = true;
      stack.push(current);
      current = [nr, nc];
    } else {
      current = stack.pop()!;
    }
  }

  grid[0][0].top = false;
  grid[rows - 1][cols - 1].bottom = false;

  return grid;
}

// ── Word Search ────────────────────────────────────────────────

// Theme-aware word banks for Islamic educational content
const THEME_WORD_BANK: Record<string, string[]> = {
  ramadan: ["RAMADAN", "FAST", "IFTAR", "SUHOOR", "QURAN", "PRAYER", "MOSQUE", "DATES"],
  eid: ["EID", "SALAH", "GIFTS", "FAMILY", "HAPPY", "MOSQUE", "PRAY", "SHARE"],
  mosque: ["MOSQUE", "MINARET", "DOME", "PRAYER", "WUDU", "IMAM", "QURAN", "SALAH"],
  arabic: ["ALIF", "BA", "TA", "ARABIC", "WRITE", "READ", "LEARN", "LETTER"],
  quran: ["QURAN", "SURAH", "AYAH", "READ", "RECITE", "LEARN", "BOOK", "HAFIZ"],
  kindness: ["KIND", "SHARE", "HELP", "LOVE", "CARE", "GIVE", "SMILE", "FRIEND"],
  patience: ["SABR", "WAIT", "CALM", "PEACE", "TRUST", "HOPE", "PRAY", "FAITH"],
  gratitude: ["SHUKR", "THANKS", "HAPPY", "GIFT", "BLESSED", "PRAISE", "SMILE", "JOY"],
  hajj: ["HAJJ", "KAABA", "MINA", "ARAFAT", "TAWAF", "IHRAM", "PRAY", "PILGRIM"],
  pillars: ["SALAH", "ZAKAT", "SAWM", "HAJJ", "FAITH", "PRAYER", "GIVE", "FAST"],
  default: ["SALAH", "QURAN", "MOSQUE", "KIND", "LEARN", "SHARE", "PRAY", "FAITH"],
};

function getThemeWords(theme: string): string[] {
  const lower = theme.toLowerCase();

  for (const [key, words] of Object.entries(THEME_WORD_BANK)) {
    if (lower.includes(key)) {
      return words.slice(0, 7);
    }
  }

  // Build custom word list: theme word + default Islamic words
  const themeWord = theme.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 7);
  const result = themeWord.length >= 3 ? [themeWord] : [];
  const defaults = THEME_WORD_BANK.default;

  for (const w of defaults) {
    if (result.length >= 7) break;
    if (!result.includes(w)) result.push(w);
  }

  return result;
}

function drawWordSearch(doc: PDFKit.PDFDocument, theme: string) {
  doc
    .fontSize(18)
    .font("Helvetica-Bold")
    .fillColor("#333333")
    .text(`Word Search: ${theme}`, { align: "center" });
  doc.moveDown(0.4);

  const words = getThemeWords(theme);

  doc
    .fontSize(11)
    .font("Helvetica")
    .fillColor("#666666")
    .text("Find these Islamic words in the grid:", { align: "center" });
  doc.moveDown(0.3);
  doc
    .fontSize(11)
    .font("Helvetica-Bold")
    .fillColor("#0d9488")
    .text(words.join("   "), { align: "center" });
  doc.moveDown(0.8);
  doc.fillColor("#000000");

  const gridSize = 13;
  const cellSize = 30;
  const startX = (595 - gridSize * cellSize) / 2;
  const startY = doc.y + 10;

  const grid = createWordSearchGrid(gridSize, words);

  doc.font("Courier-Bold").fontSize(14);

  for (let r = 0; r < gridSize; r++) {
    for (let c = 0; c < gridSize; c++) {
      const x = startX + c * cellSize;
      const y = startY + r * cellSize;

      doc.strokeColor("#e5e0d8").lineWidth(0.5).rect(x, y, cellSize, cellSize).stroke();
      doc.fillColor("#333333").text(grid[r][c], x, y + 8, {
        width: cellSize,
        align: "center",
      });
    }
  }

  // Name field below grid
  const afterGrid = startY + gridSize * cellSize + 20;
  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#999999")
    .text(
      "Name: _______________________    Date: _______________",
      50,
      afterGrid,
      { width: 495, align: "center" }
    );
}

function createWordSearchGrid(size: number, words: string[]): string[][] {
  const grid: string[][] = Array.from({ length: size }, () =>
    Array.from({ length: size }, () => "")
  );

  const directions = [
    [0, 1],
    [1, 0],
    [1, 1],
    [0, -1],
    [-1, 0],
  ];

  let seed = 42 + words.length;
  function random() {
    seed = (seed * 16807 + 0) % 2147483647;
    return (seed - 1) / 2147483646;
  }

  for (const word of words) {
    let placed = false;
    for (let attempt = 0; attempt < 200 && !placed; attempt++) {
      const dir = directions[Math.floor(random() * directions.length)];
      const r = Math.floor(random() * size);
      const c = Math.floor(random() * size);

      if (canPlace(grid, word, r, c, dir[0], dir[1], size)) {
        for (let i = 0; i < word.length; i++) {
          grid[r + i * dir[0]][c + i * dir[1]] = word[i];
        }
        placed = true;
      }
    }
  }

  const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  for (let r = 0; r < size; r++) {
    for (let c = 0; c < size; c++) {
      if (!grid[r][c]) {
        grid[r][c] = letters[Math.floor(random() * 26)];
      }
    }
  }

  return grid;
}

function canPlace(
  grid: string[][],
  word: string,
  r: number,
  c: number,
  dr: number,
  dc: number,
  size: number
): boolean {
  for (let i = 0; i < word.length; i++) {
    const nr = r + i * dr;
    const nc = c + i * dc;
    if (nr < 0 || nr >= size || nc < 0 || nc >= size) return false;
    if (grid[nr][nc] && grid[nr][nc] !== word[i]) return false;
  }
  return true;
}

// ── Shared drawing helpers ─────────────────────────────────────

function drawStar(
  doc: PDFKit.PDFDocument,
  cx: number,
  cy: number,
  outerR: number,
  innerR: number,
  points: number,
  color: string
) {
  doc.strokeColor(color).lineWidth(1.5);
  const step = Math.PI / points;

  const coords: { x: number; y: number }[] = [];
  for (let i = 0; i < 2 * points; i++) {
    const r = i % 2 === 0 ? outerR : innerR;
    const angle = i * step - Math.PI / 2;
    coords.push({
      x: cx + Math.cos(angle) * r,
      y: cy + Math.sin(angle) * r,
    });
  }

  doc.moveTo(coords[0].x, coords[0].y);
  for (let i = 1; i < coords.length; i++) {
    doc.lineTo(coords[i].x, coords[i].y);
  }
  doc.lineTo(coords[0].x, coords[0].y);
  doc.stroke();
}
