export interface Name99 {
  arabic: string;
  transliteration: string;
  meaningEn: string;
  meaningNl: string;
  category: "majesty" | "beauty" | "perfection" | "uniqueness";
}

export const NAMES_99: Name99[] = [
  { arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaningEn: "The Most Gracious", meaningNl: "De Meest Genadige", category: "beauty" },
  { arabic: "الرَّحِيمُ", transliteration: "Ar-Raheem", meaningEn: "The Most Merciful", meaningNl: "De Meest Barmhartige", category: "beauty" },
  { arabic: "المَلِكُ", transliteration: "Al-Malik", meaningEn: "The King", meaningNl: "De Koning", category: "majesty" },
  { arabic: "القُدُّوسُ", transliteration: "Al-Quddus", meaningEn: "The Most Holy", meaningNl: "De Meest Heilige", category: "perfection" },
  { arabic: "السَّلَامُ", transliteration: "As-Salam", meaningEn: "The Source of Peace", meaningNl: "De Bron van Vrede", category: "beauty" },
  { arabic: "المُؤْمِنُ", transliteration: "Al-Mu'min", meaningEn: "The Guardian of Faith", meaningNl: "De Beschermer van Geloof", category: "beauty" },
  { arabic: "المُهَيْمِنُ", transliteration: "Al-Muhaymin", meaningEn: "The Protector", meaningNl: "De Beschermer", category: "majesty" },
  { arabic: "العَزِيزُ", transliteration: "Al-Aziz", meaningEn: "The Mighty", meaningNl: "De Machtige", category: "majesty" },
  { arabic: "الجَبَّارُ", transliteration: "Al-Jabbar", meaningEn: "The Compeller", meaningNl: "De Overweldiger", category: "majesty" },
  { arabic: "المُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaningEn: "The Greatest", meaningNl: "De Grootste", category: "majesty" },
  { arabic: "الخَالِقُ", transliteration: "Al-Khaliq", meaningEn: "The Creator", meaningNl: "De Schepper", category: "perfection" },
  { arabic: "البَارِئُ", transliteration: "Al-Bari", meaningEn: "The Evolver", meaningNl: "De Voortbrenger", category: "perfection" },
  { arabic: "المُصَوِّرُ", transliteration: "Al-Musawwir", meaningEn: "The Fashioner", meaningNl: "De Vormgever", category: "perfection" },
  { arabic: "الغَفَّارُ", transliteration: "Al-Ghaffar", meaningEn: "The Forgiver", meaningNl: "De Vergever", category: "beauty" },
  { arabic: "القَهَّارُ", transliteration: "Al-Qahhar", meaningEn: "The Subduer", meaningNl: "De Onderwerper", category: "majesty" },
  { arabic: "الوَهَّابُ", transliteration: "Al-Wahhab", meaningEn: "The Bestower", meaningNl: "De Schenker", category: "beauty" },
  { arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaningEn: "The Provider", meaningNl: "De Voorziener", category: "beauty" },
  { arabic: "الفَتَّاحُ", transliteration: "Al-Fattah", meaningEn: "The Opener", meaningNl: "De Opener", category: "perfection" },
  { arabic: "العَلِيمُ", transliteration: "Al-Alim", meaningEn: "The All-Knowing", meaningNl: "De Alwetende", category: "perfection" },
  { arabic: "السَّمِيعُ", transliteration: "As-Sami", meaningEn: "The All-Hearing", meaningNl: "De Alhorende", category: "perfection" },
  { arabic: "البَصِيرُ", transliteration: "Al-Basir", meaningEn: "The All-Seeing", meaningNl: "De Alziende", category: "perfection" },
  { arabic: "الحَكَمُ", transliteration: "Al-Hakam", meaningEn: "The Judge", meaningNl: "De Rechter", category: "majesty" },
  { arabic: "العَدْلُ", transliteration: "Al-Adl", meaningEn: "The Just", meaningNl: "De Rechtvaardige", category: "perfection" },
  { arabic: "اللَّطِيفُ", transliteration: "Al-Latif", meaningEn: "The Subtle One", meaningNl: "De Subtiele", category: "beauty" },
  { arabic: "الخَبِيرُ", transliteration: "Al-Khabir", meaningEn: "The All-Aware", meaningNl: "De Albewuste", category: "perfection" },
  { arabic: "الحَلِيمُ", transliteration: "Al-Halim", meaningEn: "The Forbearing", meaningNl: "De Verdraagzame", category: "beauty" },
  { arabic: "العَظِيمُ", transliteration: "Al-Azim", meaningEn: "The Magnificent", meaningNl: "De Grandioze", category: "majesty" },
  { arabic: "الغَفُورُ", transliteration: "Al-Ghafur", meaningEn: "The All-Forgiving", meaningNl: "De Alvergevende", category: "beauty" },
  { arabic: "الشَّكُورُ", transliteration: "Ash-Shakur", meaningEn: "The Grateful", meaningNl: "De Dankbare", category: "beauty" },
  { arabic: "العَلِيُّ", transliteration: "Al-Ali", meaningEn: "The Most High", meaningNl: "De Allerhoogste", category: "majesty" },
  { arabic: "الكَبِيرُ", transliteration: "Al-Kabir", meaningEn: "The Most Great", meaningNl: "De Allergrootste", category: "majesty" },
  { arabic: "الحَفِيظُ", transliteration: "Al-Hafiz", meaningEn: "The Preserver", meaningNl: "De Beschermer", category: "beauty" },
  { arabic: "المُقِيتُ", transliteration: "Al-Muqit", meaningEn: "The Nourisher", meaningNl: "De Voeder", category: "beauty" },
  { arabic: "الكَرِيمُ", transliteration: "Al-Karim", meaningEn: "The Generous", meaningNl: "De Gulle", category: "beauty" },
  { arabic: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaningEn: "The Watchful", meaningNl: "De Waakzame", category: "perfection" },
  { arabic: "المُجِيبُ", transliteration: "Al-Mujib", meaningEn: "The Responsive", meaningNl: "De Verhorende", category: "beauty" },
  { arabic: "الوَاسِعُ", transliteration: "Al-Wasi", meaningEn: "The All-Encompassing", meaningNl: "De Alomvattende", category: "perfection" },
  { arabic: "الحَكِيمُ", transliteration: "Al-Hakim", meaningEn: "The Wise", meaningNl: "De Wijze", category: "perfection" },
  { arabic: "الوَدُودُ", transliteration: "Al-Wadud", meaningEn: "The Loving", meaningNl: "De Liefdevolle", category: "beauty" },
  { arabic: "النُّورُ", transliteration: "An-Nur", meaningEn: "The Light", meaningNl: "Het Licht", category: "uniqueness" },
  { arabic: "الحَقُّ", transliteration: "Al-Haqq", meaningEn: "The Truth", meaningNl: "De Waarheid", category: "uniqueness" },
  { arabic: "الوَكِيلُ", transliteration: "Al-Wakil", meaningEn: "The Trustee", meaningNl: "De Vertrouweling", category: "beauty" },
  { arabic: "القَوِيُّ", transliteration: "Al-Qawiy", meaningEn: "The Strong", meaningNl: "De Sterke", category: "majesty" },
  { arabic: "الوَلِيُّ", transliteration: "Al-Wali", meaningEn: "The Protector", meaningNl: "De Beschermheer", category: "beauty" },
  { arabic: "الحَمِيدُ", transliteration: "Al-Hamid", meaningEn: "The Praiseworthy", meaningNl: "De Prijzenswaardige", category: "perfection" },
  { arabic: "التَّوَّابُ", transliteration: "At-Tawwab", meaningEn: "The Acceptor of Repentance", meaningNl: "De Aanvaerder van Berouw", category: "beauty" },
  { arabic: "الصَّبُورُ", transliteration: "As-Sabur", meaningEn: "The Patient", meaningNl: "De Geduldige", category: "beauty" },
  { arabic: "الأَوَّلُ", transliteration: "Al-Awwal", meaningEn: "The First", meaningNl: "De Eerste", category: "uniqueness" },
  { arabic: "الآخِرُ", transliteration: "Al-Akhir", meaningEn: "The Last", meaningNl: "De Laatste", category: "uniqueness" },
];
